### ISSUE TITLE
No callback when invalid ip:port given

### ISSUE THREAD

**Issue by itstrath** [gpittarelli/node-ssq#2]
Trying to query an ip:port that isn't a valid gameserver doesn't return a callback with an error, it just doesn't return any callback at all. 
Add another argument to the function to set a timeout in seconds?

**Comment by gpittarelli** [comment]
Nice catch, I'll add a timeout.

**Comment by gpittarelli** [comment]
ca8ac0f3b645f9ca28a4c4721f9fc3fafb3e9718

Feature added. I opted to make the timeout option a configurable property rather than a parameter to avoid having to repeat a timeout value in every function call if you want a custom timeout.
